package de.ovgu.ikus

import org.springframework.core.io.ClassPathResource
import java.util.*

object BuildInfo {
    val VERSION: String
    val BUILD_DATE: String
    val DEFAULT_PROPS: Properties

    init {
        // build.properties file will be generated by gradle
        val buildProps = Properties()
        buildProps.load(ClassPathResource("build.properties").inputStream)
        VERSION = buildProps["version"] as String
        BUILD_DATE = buildProps["date"] as String

        DEFAULT_PROPS = Properties()
        DEFAULT_PROPS.load(ClassPathResource("application.properties").inputStream)
    }
}